# Generated by Django 4.0.3 on 2022-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('IsTeacher', models.BooleanField(default=0)),
            ],
        ),
    ]
