# Generated by Django 4.0.3 on 2022-04-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ID',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.users')),
            ],
        ),
    ]
